sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t halderripan/docker-react-aws -f Dockerfile.f .

script:
  - docker run -e CI=true halderripan/docker-react-aws npm run test -- --coverage